env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  indent: ["error", 4]
  react/jsx-indent: ["error", 4]
  react/jsx-indent-props: ["error", 4]
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/jsx-filename-extension: [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }]
  react/jsx-props-no-spreading: "off"
  jsx-a11y/no-noninteractive-element-interactions: "off"
  jsx-a11y/click-events-have-key-events: "off"
